## Home Assistant view used as a secondary page used for maintenance purpose.
# GitHub repo: <https://github.com/melvinmajor/HomeAssistant-customisations>
# Author: Melvin Campos Casares
# Last updated: 26/06/2026 (DD/MM/YYYY)

kiosk_mode:
  non_admin_settings:
    hide_add_to_home_assistant: true
    hide_search: true
decluttering_templates:
  home_navbar:
    card:
      type: custom:navbar-card
      routes:
        - url: /custom-dashboard/shortcuts
          icon: mdi:lifebuoy
          label: Shortcuts
        - url: /custom-dashboard/home
          icon: mdi:home
          label: Home
          hold_action:
            action: navigate
            navigation_path: /config/devices/dashboard
        - url: /custom-dashboard/kitchen
          icon: mdi:fridge
          label: Kitchen
        - url: /custom-dashboard/vehicle
          icon: phu:volvo
          label: Vehicle
        - icon: mdi:server-minus
          label: IT
          url: /custom-dashboard/IT-server
        - icon: mdi:dots-horizontal
          label: More
          tap_action:
            action: open-popup
          popup:
            - icon: mdi:cog
              url: /config/dashboard
              label: Configuration
            - icon: mdi:update
              url: /config/updates
              label: |
                [[[
                  const updates = parseInt(states['sensor.updates']?.state) || 0;
                  return updates > 0 ? `Updates (${updates} available)` : 'No updates';
                ]]]
            - url: /dashboard-automations
              icon: mdi:robot
              label: Automations
            - icon: mdi:home-battery
              label: Maintenance
              url: /custom-maintenance
            - url: /hacs/dashboard
              icon: phu:smarthome-solver
              label: HACS
            - icon: mdi:power
              tap_action:
                action: call-service
                service: homeassistant.restart
                service_data: {}
                confirmation:
                  text: Are you sure you want to restart Home Assistant?
              label: Restart HA
          badge:
            show: |
              [[[
                return (parseInt(states['sensor.updates']?.state) || 0) > 0;
              ]]]
      mobile:
        mode: floating
        show_popup_label_backgrounds: true
        show_labels: popup_only
        position: bottom
      desktop:
        show_labels: popup_only
        show_popup_label_backgrounds: true
        position: bottom
      media_player:
        album_cover_background: true
        players:
          - entity: media_player.spotify_melvin_campos_casares
            icon: ""
          - entity: media_player.google_tv
            title: Google TV
            icon: mdi:youtube-tv
            tap_action:
              action: more-info
              entity: media_player.google_tv_2
      layout:
        auto_padding:
          enabled: true
          desktop_px: 100
          mobile_px: 60
        reflect_child_state: true
      styles: |
        .navbar.mobile.bottom {
          bottom: 5px;
        }
      haptic:
        tap_action: true
views:
  - type: sections
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Radiator thermostats
            heading_style: title
            icon: phu:aqara-thermo-e1
          - type: markdown
            content: "**Battery type:** 2x AA"
            text_only: true
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery
            name: Entrance
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_3
            name: Bathroom
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_2
            name: Office
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_4
            name: Bedroom
            vertical: false
            features_position: bottom
          - type: heading
            heading: Philips Hue Motion sensor
            heading_style: title
            icon: phu:motion-sensor
          - type: markdown
            content: "**Battery type:** 2x AAA"
            text_only: true
          - type: tile
            entity: sensor.detecteur_entree_batterie
            name: Entrance (bedroom side)
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_motion_sensor_2_batterie
            name: Entrance (office side)
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Philips Hue Smart Buttons
            heading_style: title
            icon: phu:button
          - type: markdown
            content: "**Battery type:** CR2032"
            text_only: true
          - type: tile
            entity: sensor.hue_smart_button_1_batterie
            name: Entrance
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_smart_button_3_batterie
            name: Living room
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_smart_button_2_batterie
            name: Office
            vertical: false
            features_position: bottom
          - type: heading
            heading: Philips Hue switches
            heading_style: title
            icon: phu:hue-only
          - type: markdown
            content: "**Battery type:** CR2032"
            text_only: true
          - type: vertical-stack
            cards:
              - type: heading
                heading: Hue Tap Dial
                heading_style: title
                icon: phu:tap-dial
                grid_options:
                  columns: 6
                  rows: auto
              - type: tile
                grid_options:
                  columns: 6
                  rows: 1
                entity: sensor.hue_tap_dial_switch_1_batterie
                name: Living room
                vertical: false
                features_position: bottom
            grid_options:
              columns: 6
              rows: auto
          - type: vertical-stack
            cards:
              - type: heading
                heading: Hue Dimmer
                heading_style: title
                icon: phu:dimmer-switch
                grid_options:
                  columns: 6
                  rows: auto
              - type: tile
                grid_options:
                  columns: 6
                  rows: 1
                entity: sensor.hue_dimmer_switch_1_batterie
                name: Bedroom
                vertical: false
                features_position: bottom
            grid_options:
              columns: 6
              rows: auto
      - type: grid
        cards:
          - type: heading
            heading: iRobot Roomba
            heading_style: title
            icon: phu:irobot
          - type: entities
            entities:
              - entity: vacuum.r5_d4
                name: Status
                secondary_info: last-updated
                icon: ""
              - entity: binary_sensor.r5_d4_bac_plein
                name: Bin is full?
              - entity: sensor.r5_d4_batterie
                name: Battery level
              - entity: sensor.r5_d4_cycles_de_la_batterie
                name: Battery cycle
                icon: phu:irobot
              - entity: sensor.r5_d4_temps_total_de_nettoyage
                name: Total cleaning time
            state_color: true
      - type: grid
        cards:
          - type: custom:decluttering-card
            template: home_navbar
    header:
      card:
        type: markdown
        text_only: true
        content: "## Maintenance"
    max_columns: 3
    title: Maintenance
    icon: mdi:home-battery
    cards: []
    subview: false
    visible:
      - user: 44573b9ac3d34374a5e538fbac0b175d
      - user: 712f940e040f46d8ab27b65c0040f410
    background:
      opacity: 50
      alignment: center
      size: cover
      repeat: no-repeat
      attachment: fixed
      image:
        media_content_id: media-source://image_upload/4f558534f7d571e219bc896a1422c99a
        media_content_type: image/png
        metadata:
          title: Black-Minimalist-Wallpaper-by-kensey-_WallpaperCave_.png
          thumbnail: /api/image/serve/4f558534f7d571e219bc896a1422c99a/256x256
          media_class: image
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://image_upload
    dense_section_placement: false
