## Home Assistant view used as a secondary page used for maintenance purpose.
# GitHub repo: <https://github.com/melvinmajor/HomeAssistant-customisations>
# Author: Melvin Campos Casares
# Last updated: 09/10/2026 (DD/MM/YYYY)

kiosk_mode:
  non_admin_settings:
    hide_add_to_home_assistant: true
    hide_search: true
decluttering_templates:
  home_navbar:
    card:
      type: custom:m3-nav-card
      style: floating
      label_position: below
      items:
        - name: Shortcuts
          icon: mdi:lifebuoy
          path: /custom-dashboard/shortcuts
        - name: Home
          icon: mdi:home
          path: /custom-dashboard/home
        - name: Kitchen
          icon: mdi:fridge
          path: /custom-dashboard/kitchen
        - name: Vehicle
          icon: phu:volvo
          path: /custom-dashboard/vehicle
        - name: IT
          icon: mdi:server-minus
          path: /custom-dashboard/IT-server
        - name: More
          icon: mdi:dots-horizontal
          submenu:
            - name: Configuration
              icon: mdi:cog
              path: /config/dashboard
            - name: Updates
              icon: mdi:update
              path: /config/updates
            - name: Automations
              icon: mdi:robot
              path: /dashboard-automations
            - name: Maintenance
              icon: mdi:home-battery
              path: /custom-maintenance
            - name: HACS
              icon: phu:smarthome-solver
              path: /hacs/dashboard
            - tap_action:
                action: perform-action
                perform_action: homeassistant.restart
                target: {}
              name: Restart HA
              icon: mdi:power
          badge: {}
      label_visibility: always
      size: 1
      icon_visibility: always
      item_background: false
      active_style: tint
      container_style: glass
      haptics: false
      auto_hide_on_scroll: false
      page_transition: none
      page_transition_ms: 180
      submenu_trigger: tap
      position: bottom
      breakpoint: 768
      icon_size: 24
      marker_motion: slide
      pill_size: 1
      label_size: 14
      edge_distance: 8
      container_opacity: 100
      blur: 20
      radius: 31
      max_width: fit
views:
  - type: sections
    sections:
      - type: grid
        cards:
          - type: custom:m3-battery-card
            auto_discover: false
            glass_background: true
            max_visible: 4
            include_area: []
            include_label: []
            exclude_entities: []
            entities:
              - entity: sensor.radiator_thermostat_w600_battery
                name: Entrance
              - entity: sensor.radiator_thermostat_w600_battery_3
                name: Bathroom
              - entity: sensor.radiator_thermostat_w600_battery_2
                name: Office
              - entity: sensor.radiator_thermostat_w600_battery_4
                name: Bedroom
            thresholds:
              critical: 10
              low: 20
              medium: 30
            card_version: 2.2.0
            name: Radiator thermostats (using 2x AA)
            show_healthy_toggle: true
            icon: phu:aqara-thermo-e1
          - type: custom:m3-battery-card
            auto_discover: false
            glass_background: true
            max_visible: 3
            include_area: []
            include_label: []
            exclude_entities: []
            entities:
              - entity: sensor.detecteur_entree_batterie
                name: Entrance (bedroom side)
                icon: phu:motion-sensor
              - entity: sensor.hue_motion_sensor_2_batterie
                name: Entrance (office side)
                icon: phu:motion-sensor
              - entity: sensor.myggspray_wrlss_mtn_sensor_battery
                name: Bathroom
                icon: phu:outdoor-motion
            thresholds:
              critical: 10
              low: 20
              medium: 30
            card_version: 2.2.0
            name: Motion sensors (using 2x AAA)
            show_healthy_toggle: true
            icon: mdi:motion-sensor
      - type: grid
        cards:
          - type: custom:m3-battery-card
            auto_discover: false
            glass_background: true
            max_visible: 5
            include_area: []
            include_label: []
            exclude_entities: []
            entities:
              - entity: sensor.hue_smart_button_1_batterie
                name: Entrance
                icon: phu:button
              - entity: sensor.hue_smart_button_3_batterie
                name: Living room
                icon: phu:button
              - entity: sensor.hue_smart_button_2_batterie
                name: Office
                icon: phu:button
              - entity: sensor.hue_tap_dial_switch_1_batterie
                name: Living room
                icon: phu:tap-dial
              - entity: sensor.hue_dimmer_switch_1_batterie
                name: Bedroom
                icon: phu:dimmer-switch
            thresholds:
              critical: 1
              low: 5
              medium: 10
            card_version: 2.2.0
            name: Buttons and switches (using CR2032)
            show_healthy_toggle: true
            icon: phu:friends-of-hue-aurora-dimmer-switch
      - type: grid
        cards:
          - type: custom:m3-heading-card
            style: simple
            title: iRobot Roomba
            show_icon: true
            title_size: 16
            card_version: 2.3.2
            icon: phu:irobot
          - color: state
            type: entities
            entities:
              - entity: vacuum.millenium_vacuum
                name: Status
                icon: ''
                secondary_info: last_updated
              - entity: sensor.millenium_status_message
                name: ' '
                icon: mdi:message
              - entity: sensor.millenium_battery
                name: Battery level
      - type: grid
        cards:
          - type: heading
            heading: Radiator thermostats
            heading_style: title
            icon: phu:aqara-thermo-e1
          - type: markdown
            content: '**Battery type:** 2x AA'
            text_only: true
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery
            name: Entrance
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_3
            name: Bathroom
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_2
            name: Office
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.radiator_thermostat_w600_battery_4
            name: Bedroom
            vertical: false
            features_position: bottom
          - type: heading
            heading: Philips Hue Motion sensor
            heading_style: title
            icon: phu:motion-sensor
          - type: markdown
            content: '**Battery type:** 2x AAA'
            text_only: true
          - type: tile
            entity: sensor.detecteur_entree_batterie
            name: Entrance (bedroom side)
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_motion_sensor_2_batterie
            name: Entrance (office side)
            vertical: false
            features_position: bottom
          - type: heading
            heading: Ikea Motion sensor
            heading_style: title
            icon: phu:outdoor-motion
          - type: markdown
            content: '**Battery type:** 2x AAA'
            text_only: true
          - type: tile
            entity: sensor.myggspray_wrlss_mtn_sensor_battery
            name: Bathroom
            vertical: false
            features_position: bottom
        visibility:
          - condition: state
            entity: input_boolean.dev_mode
            state: 'on'
      - type: grid
        cards:
          - type: heading
            heading: Philips Hue Smart Buttons
            heading_style: title
            icon: phu:button
          - type: markdown
            content: '**Battery type:** CR2032'
            text_only: true
          - type: tile
            entity: sensor.hue_smart_button_1_batterie
            name: Entrance
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_smart_button_3_batterie
            name: Living room
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.hue_smart_button_2_batterie
            name: Office
            vertical: false
            features_position: bottom
          - type: heading
            heading: Philips Hue switches
            heading_style: title
            icon: phu:hue-only
          - type: markdown
            content: '**Battery type:** CR2032'
            text_only: true
          - type: vertical-stack
            cards:
              - type: heading
                heading: Hue Tap Dial
                heading_style: title
                icon: phu:tap-dial
                grid_options:
                  columns: 6
                  rows: auto
              - type: tile
                grid_options:
                  columns: 6
                  rows: 1
                entity: sensor.hue_tap_dial_switch_1_batterie
                name: Living room
                vertical: false
                features_position: bottom
            grid_options:
              columns: 6
              rows: auto
          - type: vertical-stack
            cards:
              - type: heading
                heading: Hue Dimmer
                heading_style: title
                icon: phu:dimmer-switch
                grid_options:
                  columns: 6
                  rows: auto
              - type: tile
                grid_options:
                  columns: 6
                  rows: 1
                entity: sensor.hue_dimmer_switch_1_batterie
                name: Bedroom
                vertical: false
                features_position: bottom
            grid_options:
              columns: 6
              rows: auto
        visibility:
          - condition: state
            entity: input_boolean.dev_mode
            state: 'on'
      - type: grid
        cards:
          - type: custom:decluttering-card
            template: home_navbar
    header:
      card:
        type: markdown
        text_only: true
        content: '## Maintenance'
    max_columns: 3
    title: Maintenance
    icon: mdi:home-battery
    cards: []
    subview: false
    visible:
      - user: 44573b9ac3d34374a5e538fbac0b175d
      - user: 712f940e040f46d8ab27b65c0040f410
    background:
      opacity: 50
      alignment: center
      size: cover
      repeat: no-repeat
      attachment: fixed
      image:
        media_content_id: >-
          media-source://media_source/local/backgrounds/Black-Minimalist-Wallpaper-by-kensey-_WallpaperCave_.png
        media_content_type: image/png
        metadata:
          title: Black-Minimalist-Wallpaper-by-kensey-_WallpaperCave_.png
          thumbnail: null
          media_class: image
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://media_source
            - media_content_type: ''
              media_content_id: media-source://media_source/local/backgrounds
    dense_section_placement: false
